"""Markdown memo generation."""
from typing import Dict, Any
from datetime import datetime


def generate_memo(analysis: Dict[str, Any]) -> str:
    """Generate a structured markdown memo from analysis output."""
    addr = analysis.get("address", "Unknown")
    inputs = analysis.get("inputs", {})
    val = analysis.get("valuation", {})
    scen = analysis.get("scenario", {})
    facts = analysis.get("extracted_facts", {})
    strategy_name = analysis.get("strategy_name", "Unknown")

    price = inputs.get("price", 0)
    hold = inputs.get("hold_years", 5)

    lines = [
        f"# Deal Memo: {addr}",
        "",
        f"**Date:** {datetime.now().strftime('%Y-%m-%d')}",
        f"**Strategy:** {strategy_name}",
        f"**Hold Period:** {hold} years",
        "",
        "---",
        "",
        "## 1. Extracted Facts",
        "",
    ]

    if facts:
        for k, v in facts.items():
            if v is not None and v != []:
                if isinstance(v, list):
                    lines.append(f"- **{k.replace('_', ' ').title()}:**")
                    for item in v[:5]:
                        lines.append(f"  - {item}")
                else:
                    lines.append(f"- **{k.replace('_', ' ').title()}:** {v}")
    else:
        lines.append("_No PDF facts extracted. Manual input used._")

    lines.extend([
        "",
        "---",
        "",
        "## 2. Valuation",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Asking Price | £{price:,.0f} |",
        f"| Low Fair Value | £{val.get('low_fair_value', 0):,.0f} |",
        f"| Base Fair Value | £{val.get('base_fair_value', 0):,.0f} |",
        f"| High Fair Value | £{val.get('high_fair_value', 0):,.0f} |",
        f"| Max Bid | £{val.get('max_bid', 0):,.0f} |",
        f"| vs Base | {val.get('margin_pct', 0):.1f}% |",
        f"| Flag | **{val.get('flag', 'unknown').upper()}** |",
        "",
        "---",
        "",
        "## 3. Scenario Analysis",
        "",
        f"| Item | Value |",
        f"|------|-------|",
        f"| Entry Price | £{scen.get('entry_price', 0):,.0f} |",
        f"| Capex Estimate | £{scen.get('capex_estimate', 0):,.0f} |",
        f"| Exit Valuation | £{scen.get('exit_valuation', 0):,.0f} |",
        f"| Gross Profit | £{scen.get('gross_profit', 0):,.0f} |",
        f"| ROI | {scen.get('roi_pct', 0):.1f}% |",
        f"| Annualized ROI | {scen.get('annualized_roi_pct', 0):.1f}% |",
        f"| Max Bid | £{scen.get('max_bid', 0):,.0f} |",
        "",
        "---",
        "",
        "## 4. Verdict",
        "",
    ])

    flag = val.get("flag", "unknown")
    if flag == "underpay":
        lines.append(
            f"🟢 **UNDERPAY** — Price (£{price:,.0f}) is {val.get('margin_pct', 0):.1f}% below base fair value. "
            "Attractive entry if facts check out."
        )
    elif flag == "overpay":
        lines.append(
            f"🔴 **OVERPAY** — Price (£{price:,.0f}) is {val.get('margin_pct', 0):.1f}% above base fair value. "
            f"Max bid should be £{val.get('max_bid', 0):,.0f} or lower."
        )
    else:
        lines.append(
            f"🟡 **FAIR** — Price (£{price:,.0f}) sits within the fair value band. "
            "Deal depends on execution quality and upside thesis."
        )

    lines.extend([
        "",
        "---",
        "",
        "## 5. Contradictions & Open Questions",
        "",
        "- [ ] Verify rental demand in this micro-location",
        "- [ ] Confirm capex estimates with contractor quotes",
        "- [ ] Check planning permissions if relevant",
        "- [ ] Validate comparable sales within 0.5 mile, 6 months",
        "",
        "---",
        "",
        "_Generated by Real Estate DD Analyzer v1.0_",
    ])

    return "\n".join(lines)
